import Header from '../components/header';
import '../index.css';
import { CryptoProvider } from './context/crypto';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<CryptoProvider>
					<Header />
					<main style={{ backgroundColor: `rgba(24, 25, 27, 1)` }}>{children}</main>
				</CryptoProvider>
			</body>
		</html>
	);
}
